
require('settings')
require('mapping')
require('colorscheme-config.github')
require('packer-config')
require('nvim-tree-config')
require('lualine-config')
require('treesitter')
require('indent')
require('nvim-comment')
require('autopairs')
require('lsp-config')
require('lsp-config.cmp')
