# Move the directory to the second line
format = '$hostname#$username$git_branch$directory$character'

[character]
success_symbol = '[➜](bold white) '
error_symbol = '[✗](bold red) '

[username]
style_user = 'white bold'
style_root = 'black bold'
format = '[$user]($style) '
disabled = false
show_always = true

[hostname]
ssh_only = false
format = '[$ssh_symbol](bold blue)[$hostname](bold red)'
trim_at = '.companyname.com'
disabled = false

[git_branch]
symbol = ''
format = '\($branch\) '
truncation_length = 4
truncation_symbol = ''
