format = """
$username\
$directory\
$git_branch\
$git_status\
$nodejs\
$rust\
$python\
$docker_context\
$time\
[ ]()\
"""

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "fg:#9A348E"
style_root = "fg:#9A348E"
format = '[$user ]($style)'

[directory]
style = "fg:#DA627D"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[docker_context]
symbol = " "
style = "fg:#06969A"
format = '[ $symbol $context ]($style) $path'

[git_branch]
symbol = ""
style = "fg:#FCA17D"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "fg:#FCA17D"
format = '[$all_status$ahead_behind ]($style)'

[nodejs]
symbol = ""
style = "fg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "fg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = " "
pyenv_version_name = true
python_binary = ["./venv/bin/python", "python", "python3", "python2"]

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "fg:#33658A"
format = '[ ♥ $time ]($style)'

