format = """
$username\
$directory\
$git_branch\
$line_break
$character"""

[directory]
style = "white"

[character]
success_symbol = "[❯](white)"
error_symbol = "[❯](white)"
vimcmd_symbol = "[❮](white)"

[git_branch]
format = "[$branch]($style)"
style = "white"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "white"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "white"

[cmd_duration]
format = "[$duration]($style) "
style = "white"

[python]
format = "[$virtualenv]($style) "
style = "white"
