#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

feh --no-fehbg --bg-fill ~/dotfiles/theme/images/bg.jpg

pkill picom
picom -b --config $HOME/.config/picom/picom.conf &

xinput --set-prop "Logitech G203 LIGHTSYNC Gaming Mouse" "libinput Accel Speed" -1 &
greenclip daemon &
sh ~/.config/polybar/launch.sh &
xfce4-power-manager &
xsetroot -cursor_name left_ptr
nm-applet &
blueman-applet &

wmname LG3D &

pkill dunst
dunst -conf ~/.config/dunst/dunstrc &

bspc monitor -d 1 2 3 4 5

bspc config focused_border_color    \#c24e48
bspc config normal_border_color     \#461a22

bspc config left_padding 0
bspc config border_width 1
bspc config window_gap 20
bspc config split_ratio 0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Google-chrome desktop='^1'
bspc rule -a Wezterm state=fullscreen desktop='^7' focus=o
bspc rule -a Android-studio state=floating border=off follow=on
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
pkill borders ; borders &
