
require('settings')
require('mapping')
require('colorscheme-config.onedark_')
require('packer-config')
require('teloscope-config')
require('lualine-config')
require('treesitter')
require('indent')
require('nvim-comment')
require('autopairs')
require('lsp-config')
require('lsp-config.cmp')
require('closetag')
require('config.dashboard')

require("luasnip.loaders.from_snipmate").load()
